### ISSUE TITLE
HCX ARM Issue

### ISSUE THREAD

**Issue by Trevor-Davis** [Azure/Enterprise-Scale-for-AVS#63] opened 2021-11-24 00:39 UTC
![image](https://user-images.githubusercontent.com/56545070/143150457-49f1d415-07c8-4372-aa06-f72fbb142597.png)
this error pops when using the AVS Private Cloud w/ the HCX addon ARM template.

**Comment by ScottHolden** [comment] 2021-11-24 01:51
This looks to be a bug in the resource provider (within the validation logic), the arm calls match the rest api specs that have been published. Let me raise this with engineering directly.

(Duplicate of #59 )

**Comment by Trevor-Davis** [comment] 2021-11-24 01:52
Yeah, it's odd.  When I use the ARM template to just add HCX to an existing private cloud, works perfect.


Trevor Davis, Global Black Belt - Azure VMware Solution
954.854.2362  |  ***@***.******@***.***>
***@***.***

**Comment by poomnupong** [comment] 2021-12-01 21:44
+1 with @Trevor-Davis.
My test - enable HCX on existing AVS - complete successfully without error.

**Closed** 2022-06-28 20:28 UTC
Labels: bug
