### ISSUE TITLE
HCX w/ PC errors

### ISSUE THREAD

**Issue by Trevor-Davis** [Azure/Enterprise-Scale-for-AVS#59] opened 2021-11-08 19:04 UTC
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/56545070/140802129-81fcb8ea-76ee-4dfc-a3de-43afcbed1b09.png)
receive this error when using the private cloud w/ HCX template.

**Comment by ScottHolden** [comment] 2021-11-08 21:57
I'll have a look at this today for you.

**Comment by prasad3017** [comment] 2021-11-11 20:25
Hello Trevor, We will be providing update soon on this. 
@ScottHolden

**Comment by ScottHolden** [comment] 2021-11-30 22:38
Closing as duplicate of #63, this has been raised with engineering.

**Closed by ScottHolden** 2021-11-30 22:38 UTC
